parameters:
    app.range_months: 3
    app.post.delay: 86400
    app.post.max_count: 10
    app.fun:
        Browsers:
            Mozilla Firefox: [firefox, firefox-developer-edition]
            Chromium: [chromium, google-chrome]
            Konqueror: [kdebase-konqueror, konqueror]
            Midori: midori
            GNOME Web: epiphany
            Opera: opera
            Vivaldi: vivaldi
            Brave: brave-bin
            surf: surf
        Editors:
            Vim: [vim, gvim, neovim]
            Emacs: [emacs, xemacs]
            Nano: nano
            Gedit: gedit
            Kate: [kdesdk-kate, kate]
            Kwrite: [kdebase-kwrite, kwrite]
            Vi: vi
            Mousepad: mousepad
            Leafpad: leafpad
            Geany: geany
            Pluma: pluma
        Desktop Environments:
            KDE SC: [kdebase-workspace, plasma-workspace, plasma-desktop]
            GNOME: gnome-shell
            LXDE: lxde-common
            Xfce: xfdesktop
            Enlightenment: [enlightenment, enlightenment16]
            MATE: mate-panel
            Cinnamon: cinnamon
            Deepin: deepin-wm
        File Managers:
            Dolphin: [kdebase-dolphin, dolphin]
            Konqueror: [kdebase-konqueror, konqueror]
            MC: mc
            GNOME Files: nautilus
            PCManFM: pcmanfm
            Thunar: thunar
            Caja: caja
            Nemo: nemo
        Window Managers:
            Openbox: openbox
            Fluxbox: fluxbox
            I3: i3-wm
            awesome: awesome
        Shells:
            Bash: bash
            Dash: dash
            Zsh: zsh
            Fish: fish
            Tcsh: tcsh
        Graphic Chipsets:
            AMD: [xf86-video-ati, xf86-video-r128, xf86-video-mach64, xf86-video-amdgpu]
            NVIDIA: [nvidia-utils, nvidia-390xx-utils, nvidia-304xx-utils, xf86-video-nouveau, xf86-video-nv]
            Intel: [xf86-video-intel, xf86-video-i740]
        Runtime Environment:
            PHP: php
            Ruby: ruby
            Perl: perl
            Java: java-environment-common
            Python: python
            Node.js: nodejs
            Lua: lua
            Bash: bash
