version: "3"

volumes:
  db-socket:
  db-data:

services:
  app:
    build: docker/app
    working_dir: /app
    environment:
      - HOME=/tmp
    command: php -S 0.0.0.0:8180 -t /app/public
    user: "1000"
    ports:
      - "8180:8180"
    volumes:
      - .:/app
      - db-socket:/run/mysqld
    tmpfs:
      - /tmp
    depends_on:
      - db

  assets:
    build: docker/app
    working_dir: /app
    environment:
      - HOME=/tmp
    command: node_modules/.bin/encore dev-server --host 0.0.0.0 --public localhost --port 8181 --disable-host-check --inline=false
    user: "1000"
    ports:
      - "8181:8181"
    volumes:
      - .:/app
    tmpfs:
      - /tmp

  db:
    build: docker/db
    command: mysqld
    user: mysql
    network_mode: none
    volumes:
      - db-data:/var/lib/mysql
      - db-socket:/run/mysqld
    tmpfs:
      - /tmp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7.7-1
    environment:
      - PMA_HOST=localhost
      - PMA_USER=root
      - PMA_PASSWORD=
    ports:
      - "8190:80"
    volumes:
      - db-socket:/run/mysqld
    tmpfs:
      - /tmp
    depends_on:
      - db
